---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master-headless
  namespace: logging
  labels:
    app: elasticsearch-master
spec:
  clusterIP: None
  selector:
    app: elasticsearch-master
  ports:
    - name: https
      port: 9200
      protocol: TCP
    - name: transport
      port: 9300
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: logging
  labels:
    app: elasticsearch-master
spec:
  type: ClusterIP
  selector:
    app: elasticsearch-master
  ports:
    - name: https
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: 9300
      protocol: TCP
...


  